/* ============================================================
   ✏️ THIS IS THE ONLY FILE YOU EVER NEED TO EDIT.

   To remove a restaurant: delete its line.
   To add one: copy any line and change the text.
   Only `name` is required — `cuisine` and `dish` are optional.
   ============================================================ */

// Added to searches only when the visitor's location is unavailable.
const CITY_HINT = "Dubai";

const RESTAURANTS = [
  { name: "72 Mala Station", cuisine: "Asian", dish: "Spicy sour soup" },
  { name: "77 Asia", cuisine: "Asian", dish: "Thai basil stir fry" },
  { name: "Adaminde Chayakada", cuisine: "Biryani", dish: "Bamboo biryani chicken" },
  { name: "Akabare Thakali Restaurant", cuisine: "Asian", dish: "Chow mein" },
  { name: "Al Twar Tea Junction Restaurant", cuisine: "Cafeteria", dish: "Chicken burger with mojito" },
  { name: "Arabian Grill Restaurant", cuisine: "Middle Eastern", dish: "Zinker and Pepsi combo" },
  { name: "Arheb Restaurant", cuisine: "Middle Eastern", dish: "Chicken fried rice/noodles" },
  { name: "Aylla Cafe", cuisine: "Burgers", dish: "Aylla fish fillet burger" },
  { name: "B60 Burgers", cuisine: "Burgers", dish: "Chicken burger meal" },
  { name: "Barbecue Delights", cuisine: "Chicken & Grill", dish: "Chicken reshmi kabab" },
  { name: "Baskin Robbins", cuisine: "Desserts & Sweets", dish: "Kids scoop sundae" },
  { name: "Banarasi Chaat and Kulfi Wala", cuisine: "Chaat & Street Food", dish: "Bhel poori" },
  { name: "Bella Chai", cuisine: "Coffee & Tea", dish: "Bun kebab and bubble tea" },
  { name: "Bella Italo", cuisine: "International", dish: "Bella pasta" },
  { name: "Best Peak Ice Cream Shop", cuisine: "Desserts & Sweets", dish: "Matcha Cloud Bliss" },
  { name: "Bikanervala", cuisine: "Chaat & Street Food", dish: "Dahi puri" },
  { name: "Blue Mountain Restaurant", cuisine: "Cafeteria", dish: "Chicken burger and Pepsi" },
  { name: "Bo", cuisine: "Asian", dish: "Nem" },
  { name: "Bounty Beets – Le Meridien Mina Seyahi", cuisine: "Hotel Dining", dish: "Tomato crostini" },
  { name: "Bubee Drinks Cafe", cuisine: "Coffee & Tea", dish: "Mango lemon tea" },
  { name: "Burger King", cuisine: "Burgers", dish: "Mix N Match" },
  { name: "Burger Spot", cuisine: "Burgers", dish: "Burger shawarma and drink" },
  { name: "Café Barbera", cuisine: "Desserts & Sweets", dish: "Two scoop Italian gelato" },
  { name: "Cafe Calicut", cuisine: "Chicken & Grill", dish: "Peri Peri BBQ wings" },
  { name: "Cafe Kkai", cuisine: "Coffee & Tea", dish: "Coffee and brownie" },
  { name: "Cake Lake Bakery", cuisine: "Bakery", dish: "Special brownies" },
  { name: "Caramalize", cuisine: "Bakery", dish: "Assorted brownie bites" },
  { name: "Caribou Coffee", cuisine: "Coffee & Tea", dish: "Americano and croissant" },
  { name: "Ćevapi Bosnian", cuisine: "International", dish: "Pljeskavica" },
  { name: "City Corner Cafeteria", cuisine: "Cafeteria", dish: "Zinger burger and juice" },
  { name: "Cold Stone Creamery", cuisine: "Desserts & Sweets", dish: "Birthday cake remix" },
  { name: "Costa Coffee", cuisine: "Coffee & Tea", dish: "Choco swirl and Americano" },
  { name: "Chaat Bazaar", cuisine: "Chaat & Street Food", dish: "Chaat Lovers combo" },
  { name: "Chai and Co.", cuisine: "Coffee & Tea", dish: "Saffron milk cafe" },
  { name: "Cahiiwala Of London", cuisine: "Chaat & Street Food", dish: "Samosa chaat" },
  { name: "Chauddagram Restaurant", cuisine: "Biryani", dish: "Beef pulau" },
  { name: "Cut in Half", cuisine: "Snacks", dish: "OG fries" },
  { name: "Curry Pot Restaurant", cuisine: "Indian", dish: "DSS Special kebab stick" },
  { name: "Delhi Highway", cuisine: "Indian", dish: "Chole Chawal combo" },
  { name: "Desi Compass Restaurant and Cafe", cuisine: "Indian", dish: "Butter chicken meal" },
  { name: "Desi & Co", cuisine: "Biryani", dish: "Chicken biryani" },
  { name: "Desi Mehfil", cuisine: "Biryani", dish: "Chicken biryani" },
  { name: "Dhaba Lane", cuisine: "Biryani", dish: "Dum chicken biryani" },
  { name: "Dodo Pizza", cuisine: "Pizza", dish: "Medium margherita pizza" },
  { name: "Dunkin'", cuisine: "Coffee & Tea", dish: "Medium iced coffee and doughnut" },
  { name: "El Moreno", cuisine: "Desserts & Sweets", dish: "Churros" },
  { name: "El Sur – The Westin Dubai Mina Seyahi", cuisine: "Hotel Dining", dish: "Tortilla de Patatas" },
  { name: "Feka", cuisine: "Middle Eastern", dish: "Iraqi Kebab Arouq" },
  { name: "FiLLi", cuisine: "Coffee & Tea", dish: "Foodles or bubble tea" },
  { name: "Foodex Real Taste", cuisine: "Indian", dish: "Chicken fry combo or lemon juice" },
  { name: "Fowli Chicken Shop", cuisine: "Chicken & Grill", dish: "Big Mozz Crispy Bars" },
  { name: "Gelato Divino", cuisine: "Desserts & Sweets", dish: "Classico cup and two toppings" },
  { name: "Grand Mehfil Restaurant", cuisine: "Biryani", dish: "Chicken dum biryani" },
  { name: "Green City Restaurant", cuisine: "Burgers", dish: "Chicken or beef burger" },
  { name: "Green Land", cuisine: "Biryani", dish: "Chicken biryani" },
  { name: "Green Land Restaurant", cuisine: "Burgers", dish: "Chicken or beef burger" },
  { name: "Hangry Joe's", cuisine: "Chicken & Grill", dish: "Wings" },
  { name: "Hard Rock Cafe", cuisine: "Desserts & Sweets", dish: "Famous fudge brownie" },
  { name: "Highway 311 Grills and Eatery", cuisine: "International", dish: "Burrito" },
  { name: "Hillhouse Brasserie", cuisine: "International", dish: "Bacon and cheese croquettes" },
  { name: "Hot 'N' Cool", cuisine: "Cafeteria", dish: "Sandwich and juice" },
  { name: "House of Pops", cuisine: "Desserts & Sweets", dish: "Assorted ice pop" },
  { name: "Hussain Al Abdulla", cuisine: "Middle Eastern", dish: "Dynamite Oman zinger" },
  { name: "iCoffee", cuisine: "Coffee & Tea", dish: "Cappuccino and banana loaf" },
  { name: "illy Caffe", cuisine: "Coffee & Tea", dish: "Black coffee" },
  { name: "It's Desi", cuisine: "International", dish: "Gnocchi pasta" },
  { name: "Indian Oven – Town Square", cuisine: "Biryani", dish: "Vegetable biryani" },
  { name: "Jungle Juice", cuisine: "Healthy & Juice", dish: "Lemonade" },
  { name: "Kaiser's Vienna", cuisine: "International", dish: "Small schnitzel with salad" },
  { name: "Karachi Darbar", cuisine: "Pakistani", dish: "Chicken tikka" },
  { name: "Keerthi Restaurant", cuisine: "Indian", dish: "Shawarma and Pepsi combo" },
  { name: "Kelly's Cajun Grill", cuisine: "Chicken & Grill", dish: "Vegetable noodles" },
  { name: "Kelkina", cuisine: "International", dish: "Samsa" },
  { name: "Keto Cafe by GBF", cuisine: "Healthy & Juice", dish: "Chicken cheese panini" },
  { name: "Key Town Restaurant", cuisine: "Chaat & Street Food", dish: "Pigodi" },
  { name: "Khau Galli", cuisine: "Chaat & Street Food", dish: "Chole Bhature" },
  { name: "Khan Gi", cuisine: "Pakistani", dish: "Chapli kabab" },
  { name: "Kozhikode Star", cuisine: "Biryani", dish: "Single chicken biryani" },
  { name: "King Chef", cuisine: "South Indian", dish: "Nadan chicken combo" },
  { name: "Koukh Al Shay", cuisine: "Middle Eastern", dish: "Zinger wrap" },
  { name: "Lacabite Bakery and Arabic Sweets", cuisine: "Bakery", dish: "Turkish milk cake" },
  { name: "Lahori Sweets Restaurant", cuisine: "Desserts & Sweets", dish: "Peshawari surprise" },
  { name: "LDC Kitchen and Coffee", cuisine: "Healthy & Juice", dish: "Quinoa and falafel bowl" },
  { name: "Macunadas Empanadas Argentinas", cuisine: "International", dish: "Cheese empanada" },
  { name: "Maestro Pizza", cuisine: "Pizza", dish: "Pick your pizza" },
  { name: "Mama Italia", cuisine: "Pizza", dish: "Margherita pizza" },
  { name: "Mamu Roti And Chai Cafe", cuisine: "Biryani", dish: "Chicken biryani" },
  { name: "Matter by iCoffee", cuisine: "Coffee & Tea", dish: "Pesto tuna confit sandwich" },
  { name: "Meet.Tang", cuisine: "Desserts & Sweets", dish: "Mixed fruit jelly soup" },
  { name: "Metro View", cuisine: "Cafeteria", dish: "Fries and avocado juice" },
  { name: "Mezbaan E Lucknow", cuisine: "Indian", dish: "Chilli chicken roll" },
  { name: "Milan Veg", cuisine: "South Indian", dish: "Mini dosa tea set" },
  { name: "Mirdif Fish and Chips", cuisine: "International", dish: "Fish and chips" },
  { name: "Mumbai Junction", cuisine: "Chaat & Street Food", dish: "Pav bhaji" },
  { name: "My Sandwich Cafeteria", cuisine: "Cafeteria", dish: "Fresh chicken burger" },
  { name: "New Sarhad Darbar", cuisine: "Biryani", dish: "Chicken biryani" },
  { name: "New York Fries", cuisine: "Snacks", dish: "Snack plain fries" },
  { name: "Nikkei Modern Japanese", cuisine: "Asian", dish: "Cheese avocado Urumaki" },
  { name: "Oporto", cuisine: "Burgers", dish: "Bondi burger" },
  { name: "Pão de Goa Restaurant & Café", cuisine: "Indian", dish: "The prawn thali" },
  { name: "Pind Da Dhaba", cuisine: "Desserts & Sweets", dish: "Malai Kulfi stick" },
  { name: "Pizza Sabbioni", cuisine: "Pizza", dish: "Margarita pizza" },
  { name: "Pret A Manger", cuisine: "Coffee & Tea", dish: "Americano and pastel de nata combo" },
  { name: "Qasar Punjab Restaurant", cuisine: "Indian", dish: "Special dal chawal" },
  { name: "Rajan Sweets and Snacks", cuisine: "Biryani", dish: "Vegetable biryani" },
  { name: "Royal Nawaab Restaurant", cuisine: "Biryani", dish: "Kabab pulao" },
  { name: "Saigon – Taste of Vietnam", cuisine: "Asian", dish: "Green papaya salad" },
  { name: "Sandwich Square", cuisine: "Chaat & Street Food", dish: "Pac bhaji" },
  { name: "Sea Shell", cuisine: "Cafeteria", dish: "Chicken burger and lime" },
  { name: "Seoul Street Cafe", cuisine: "Asian", dish: "Bingsoo mango" },
  { name: "Shaka Waka", cuisine: "Healthy & Juice", dish: "Green salad" },
  { name: "Shake Shack", cuisine: "Burgers", dish: "New York plain hot dog" },
  { name: "Shanghai Kitchen", cuisine: "Asian", dish: "Steamed Momo and iced tea" },
  { name: "Sharief Bhai – Dakhni Biryani", cuisine: "Biryani", dish: "Shawarma and mojito combo" },
  { name: "Slice – Grand Plaza Mövenpick", cuisine: "Hotel Dining", dish: "Mövenpick ice cream" },
  { name: "Soofi", cuisine: "Pakistani", dish: "Tikka pulao" },
  { name: "Spice Grill", cuisine: "Chicken & Grill", dish: "Bang Bang shrimp bowl" },
  { name: "Spice N Nice Restaurant", cuisine: "South Indian", dish: "Twist chicken nadan curry" },
  { name: "Spice Hut", cuisine: "Pizza", dish: "Zinger chicken pizza" },
  { name: "Stand View Restaurant", cuisine: "Cafeteria", dish: "Burger and juice meal" },
  { name: "Street Menu Restaurant", cuisine: "South Indian", dish: "Chicken Kothu Poratta" },
  { name: "Sthan", cuisine: "Biryani", dish: "Sthan's Lagran biryani" },
  { name: "Sumo Sushi and Bento", cuisine: "Asian", dish: "Cheese Roll and gyoza" },
  { name: "Taco Taco", cuisine: "International", dish: "Burrito bowl" },
  { name: "Taste of Malabar", cuisine: "South Indian", dish: "Club sandwich and mint lime" },
  { name: "Texas Chicken", cuisine: "Chicken & Grill", dish: "Mega bites sandwich meal" },
  { name: "The Bhukkad Cafe", cuisine: "Chaat & Street Food", dish: "Pani puri and chai combo" },
  { name: "The Bolt Hole", cuisine: "International", dish: "Beef brisket croquettes" },
  { name: "The Choco Monarch", cuisine: "Desserts & Sweets", dish: "Crepe Monarch medium" },
  { name: "The Cool Mood Cafe", cuisine: "Healthy & Juice", dish: "Your smoothie pick" },
  { name: "The Daily", cuisine: "Healthy & Juice", dish: "Rove poke bowl" },
  { name: "The GBF Shop", cuisine: "Bakery", dish: "Bagel pizza" },
  { name: "The Golden Thali Restaurant", cuisine: "Chaat & Street Food", dish: "Patti samosa" },
  { name: "The Little Fox Century Mall", cuisine: "Burgers", dish: "Fox Burger" },
  { name: "The Monk", cuisine: "Asian", dish: "Chicken chilly bao" },
  { name: "The Noodle House", cuisine: "Asian", dish: "Chicken siew mai" },
  { name: "The Permit Room", cuisine: "South Indian", dish: "Benne dosa" },
  { name: "Trattoria", cuisine: "International", dish: "Arancini di Riso" },
  { name: "UpTown Pizza and Burger", cuisine: "Pizza", dish: "Uptown classic margherita" },
  { name: "Vasai Local Restaurant", cuisine: "Biryani", dish: "Prawn biryani" },
  { name: "Violet Sweets", cuisine: "Bakery", dish: "Bento cake" },
  { name: "Veg Treat Restaurant", cuisine: "Chaat & Street Food", dish: "Veg tandoori momos" },
  { name: "Wawe", cuisine: "Coffee & Tea", dish: "V60" },
  { name: "Wok N Roll Cafe", cuisine: "Asian", dish: "Chicken steam momos" },
  { name: "White Mocha Coffee", cuisine: "Coffee & Tea", dish: "Zinger wrap" },
  { name: "Yalla Momos", cuisine: "Asian", dish: "Dimsum basket" },
  { name: "Yoko Sizzlers", cuisine: "Desserts & Sweets", dish: "Sizzling brownie" },
  { name: "Zaika", cuisine: "Chaat & Street Food", dish: "Chole Bhature" },
  { name: "Zain's Restaurant", cuisine: "South Indian", dish: "Porotta chilli combo" },
  { name: "Zest Loungge", cuisine: "Desserts & Sweets", dish: "Malai kulfi stick" },
];