/* ============================================================
   ✏️ THIS IS THE ONLY FILE YOU EVER NEED TO EDIT.

   To remove a restaurant: delete its line.
   To add one: copy any line and change the text.
   Only `name` is required — `cuisine` is optional.
   (Dishes were removed: the 10 AED deal varies per branch.)
   ============================================================ */

// Added to searches only when the visitor's location is unavailable.
const CITY_HINT = "Dubai";

const RESTAURANTS = [
  { name: "72 Mala Station", cuisine: "Asian" },
  { name: "77 Asia", cuisine: "Asian" },
  { name: "Adaminde Chayakada", cuisine: "Biryani" },
  { name: "Akabare Thakali Restaurant", cuisine: "Asian" },
  { name: "Al Twar Tea Junction Restaurant", cuisine: "Cafeteria" },
  { name: "Arabian Grill Restaurant", cuisine: "Middle Eastern" },
  { name: "Arheb Restaurant", cuisine: "Middle Eastern" },
  { name: "Aylla Cafe", cuisine: "Burgers" },
  { name: "B60 Burgers", cuisine: "Burgers" },
  { name: "Barbecue Delights", cuisine: "Chicken & Grill" },
  { name: "Baskin Robbins", cuisine: "Desserts & Sweets" },
  { name: "Banarasi Chaat and Kulfi Wala", cuisine: "Chaat & Street Food" },
  { name: "Bella Chai", cuisine: "Coffee & Tea" },
  { name: "Bella Italo", cuisine: "International" },
  { name: "Best Peak Ice Cream Shop", cuisine: "Desserts & Sweets" },
  { name: "Bikanervala", cuisine: "Chaat & Street Food" },
  { name: "Blue Mountain Restaurant", cuisine: "Cafeteria" },
  { name: "Bo", cuisine: "Asian" },
  { name: "Bounty Beets – Le Meridien Mina Seyahi", cuisine: "Hotel Dining" },
  { name: "Bubee Drinks Cafe", cuisine: "Coffee & Tea" },
  { name: "Burger King", cuisine: "Burgers" },
  { name: "Burger Spot", cuisine: "Burgers" },
  { name: "Café Barbera", cuisine: "Desserts & Sweets" },
  { name: "Cafe Calicut", cuisine: "Chicken & Grill" },
  { name: "Cafe Kkai", cuisine: "Coffee & Tea" },
  { name: "Cake Lake Bakery", cuisine: "Bakery" },
  { name: "Caramalize", cuisine: "Bakery" },
  { name: "Caribou Coffee", cuisine: "Coffee & Tea" },
  { name: "Ćevapi Bosnian", cuisine: "International" },
  { name: "City Corner Cafeteria", cuisine: "Cafeteria" },
  { name: "Cold Stone Creamery", cuisine: "Desserts & Sweets" },
  { name: "Costa Coffee", cuisine: "Coffee & Tea" },
  { name: "Chaat Bazaar", cuisine: "Chaat & Street Food" },
  { name: "Chai and Co.", cuisine: "Coffee & Tea" },
  { name: "Cahiiwala Of London", cuisine: "Chaat & Street Food" },
  { name: "Chauddagram Restaurant", cuisine: "Biryani" },
  { name: "Cut in Half", cuisine: "Snacks" },
  { name: "Curry Pot Restaurant", cuisine: "Indian" },
  { name: "Delhi Highway", cuisine: "Indian" },
  { name: "Desi Compass Restaurant and Cafe", cuisine: "Indian" },
  { name: "Desi & Co", cuisine: "Biryani" },
  { name: "Desi Mehfil", cuisine: "Biryani" },
  { name: "Dhaba Lane", cuisine: "Biryani" },
  { name: "Dodo Pizza", cuisine: "Pizza" },
  { name: "Dunkin'", cuisine: "Coffee & Tea" },
  { name: "El Moreno", cuisine: "Desserts & Sweets" },
  { name: "El Sur – The Westin Dubai Mina Seyahi", cuisine: "Hotel Dining" },
  { name: "Feka", cuisine: "Middle Eastern" },
  { name: "FiLLi", cuisine: "Coffee & Tea" },
  { name: "Foodex Real Taste", cuisine: "Indian" },
  { name: "Fowli Chicken Shop", cuisine: "Chicken & Grill" },
  { name: "Gelato Divino", cuisine: "Desserts & Sweets" },
  { name: "Grand Mehfil Restaurant", cuisine: "Biryani" },
  { name: "Green City Restaurant", cuisine: "Burgers" },
  { name: "Green Land", cuisine: "Biryani" },
  { name: "Green Land Restaurant", cuisine: "Burgers" },
  { name: "Hangry Joe's", cuisine: "Chicken & Grill" },
  { name: "Hard Rock Cafe", cuisine: "Desserts & Sweets" },
  { name: "Highway 311 Grills and Eatery", cuisine: "International" },
  { name: "Hillhouse Brasserie", cuisine: "International" },
  { name: "Hot 'N' Cool", cuisine: "Cafeteria" },
  { name: "House of Pops", cuisine: "Desserts & Sweets" },
  { name: "Hussain Al Abdulla", cuisine: "Middle Eastern" },
  { name: "iCoffee", cuisine: "Coffee & Tea" },
  { name: "illy Caffe", cuisine: "Coffee & Tea" },
  { name: "It's Desi", cuisine: "International" },
  { name: "Indian Oven – Town Square", cuisine: "Biryani" },
  { name: "Jungle Juice", cuisine: "Healthy & Juice" },
  { name: "Kaiser's Vienna", cuisine: "International" },
  { name: "Karachi Darbar", cuisine: "Pakistani" },
  { name: "Keerthi Restaurant", cuisine: "Indian" },
  { name: "Kelly's Cajun Grill", cuisine: "Chicken & Grill" },
  { name: "Kelkina", cuisine: "International" },
  { name: "Keto Cafe by GBF", cuisine: "Healthy & Juice" },
  { name: "Key Town Restaurant", cuisine: "Chaat & Street Food" },
  { name: "Khau Galli", cuisine: "Chaat & Street Food" },
  { name: "Khan Gi", cuisine: "Pakistani" },
  { name: "Kozhikode Star", cuisine: "Biryani" },
  { name: "King Chef", cuisine: "South Indian" },
  { name: "Koukh Al Shay", cuisine: "Middle Eastern" },
  { name: "Lacabite Bakery and Arabic Sweets", cuisine: "Bakery" },
  { name: "Lahori Sweets Restaurant", cuisine: "Desserts & Sweets" },
  { name: "LDC Kitchen and Coffee", cuisine: "Healthy & Juice" },
  { name: "Macunadas Empanadas Argentinas", cuisine: "International" },
  { name: "Maestro Pizza", cuisine: "Pizza" },
  { name: "Mama Italia", cuisine: "Pizza" },
  { name: "Mamu Roti And Chai Cafe", cuisine: "Biryani" },
  { name: "Matter by iCoffee", cuisine: "Coffee & Tea" },
  { name: "Meet.Tang", cuisine: "Desserts & Sweets" },
  { name: "Metro View", cuisine: "Cafeteria" },
  { name: "Mezbaan E Lucknow", cuisine: "Indian" },
  { name: "Milan Veg", cuisine: "South Indian" },
  { name: "Mirdif Fish and Chips", cuisine: "International" },
  { name: "Mumbai Junction", cuisine: "Chaat & Street Food" },
  { name: "My Sandwich Cafeteria", cuisine: "Cafeteria" },
  { name: "New Sarhad Darbar", cuisine: "Biryani" },
  { name: "New York Fries", cuisine: "Snacks" },
  { name: "Nikkei Modern Japanese", cuisine: "Asian" },
  { name: "Oporto", cuisine: "Burgers" },
  { name: "Pão de Goa Restaurant & Café", cuisine: "Indian" },
  { name: "Pind Da Dhaba", cuisine: "Desserts & Sweets" },
  { name: "Pizza Sabbioni", cuisine: "Pizza" },
  { name: "Pret A Manger", cuisine: "Coffee & Tea" },
  { name: "Qasar Punjab Restaurant", cuisine: "Indian" },
  { name: "Rajan Sweets and Snacks", cuisine: "Biryani" },
  { name: "Royal Nawaab Restaurant", cuisine: "Biryani" },
  { name: "Saigon – Taste of Vietnam", cuisine: "Asian" },
  { name: "Sandwich Square", cuisine: "Chaat & Street Food" },
  { name: "Sea Shell", cuisine: "Cafeteria" },
  { name: "Seoul Street Cafe", cuisine: "Asian" },
  { name: "Shaka Waka", cuisine: "Healthy & Juice" },
  { name: "Shake Shack", cuisine: "Burgers" },
  { name: "Shanghai Kitchen", cuisine: "Asian" },
  { name: "Sharief Bhai – Dakhni Biryani", cuisine: "Biryani" },
  { name: "Slice – Grand Plaza Mövenpick", cuisine: "Hotel Dining" },
  { name: "Soofi", cuisine: "Pakistani" },
  { name: "Spice Grill", cuisine: "Chicken & Grill" },
  { name: "Spice N Nice Restaurant", cuisine: "South Indian" },
  { name: "Spice Hut", cuisine: "Pizza" },
  { name: "Stand View Restaurant", cuisine: "Cafeteria" },
  { name: "Street Menu Restaurant", cuisine: "South Indian" },
  { name: "Sthan", cuisine: "Biryani" },
  { name: "Sumo Sushi and Bento", cuisine: "Asian" },
  { name: "Taco Taco", cuisine: "International" },
  { name: "Taste of Malabar", cuisine: "South Indian" },
  { name: "Texas Chicken", cuisine: "Chicken & Grill" },
  { name: "The Bhukkad Cafe", cuisine: "Chaat & Street Food" },
  { name: "The Bolt Hole", cuisine: "International" },
  { name: "The Choco Monarch", cuisine: "Desserts & Sweets" },
  { name: "The Cool Mood Cafe", cuisine: "Healthy & Juice" },
  { name: "The Daily", cuisine: "Healthy & Juice" },
  { name: "The GBF Shop", cuisine: "Bakery" },
  { name: "The Golden Thali Restaurant", cuisine: "Chaat & Street Food" },
  { name: "The Little Fox Century Mall", cuisine: "Burgers" },
  { name: "The Monk", cuisine: "Asian" },
  { name: "The Noodle House", cuisine: "Asian" },
  { name: "The Permit Room", cuisine: "South Indian" },
  { name: "Trattoria", cuisine: "International" },
  { name: "UpTown Pizza and Burger", cuisine: "Pizza" },
  { name: "Vasai Local Restaurant", cuisine: "Biryani" },
  { name: "Violet Sweets", cuisine: "Bakery" },
  { name: "Veg Treat Restaurant", cuisine: "Chaat & Street Food" },
  { name: "Wawe", cuisine: "Coffee & Tea" },
  { name: "Wok N Roll Cafe", cuisine: "Asian" },
  { name: "White Mocha Coffee", cuisine: "Coffee & Tea" },
  { name: "Yalla Momos", cuisine: "Asian" },
  { name: "Yoko Sizzlers", cuisine: "Desserts & Sweets" },
  { name: "Zaika", cuisine: "Chaat & Street Food" },
  { name: "Zain's Restaurant", cuisine: "South Indian" },
  { name: "Zest Loungge", cuisine: "Desserts & Sweets" },
];